[package]
name = "ruback"
version = "0.1.0"
authors = ["Marko Mikulicic <mmikulicic@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
debug = true

[dependencies]
backtrace = "0.3.59"
croaring = "0.5.0"
libc = { version = "^0.2.8", default-features = false }
tikv-jemallocator = {version = "0.4.0"}
lazy_static = "1.4.0"
pprof = "0.4.3"

# tikv-jemallocator = {version = "0.4.0", features = ["unprefixed_malloc_on_supported_platforms"] }
# tikv-jemalloc-sys = { version = "0.4", features = ["stats"] }

# deepsize = "0.2.0"
# heapsize = "0.4.2"
