[package]
name = "heappy"
version = "0.1.0"
authors = [ "Marko Mikulicic <mkm@influxdata.com>" ]
edition = "2018"

[workspace]
members = [
    "examples/complex",
    "examples/simple",
]

[profile.release]
debug = true

[features]
default = []
jemalloc_shim = []
enable_heap_profiler = [ "jemalloc_shim" ]

[dependencies]
backtrace = "0.3.59"
bytes = "1.0.1"
lazy_static = "1.4.0"
libc = { version = "^0.2.8", default-features = false }
pprof = {version = "0.4.3", features = [ "flamegraph", "protobuf" ] }
spin = "0.9.0"
tikv-jemalloc-sys = { version = "0.4", features = [ "stats" ] }
