[package]
name = "complex"
version = "0.1.0"
edition = "2018"

[dependencies]
heappy = { path = "../..", features = ["enable_heap_profiler"] }
prost = "0.7"
pprof = {version = "0.4.3", features = ["flamegraph", "protobuf"] }
croaring = "0.5.0"
